// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { changePassword, createBusiness, createUser, getBusiness, getMe, inviteBusinessMember, listBusinessMembers, listMyBusinesses, listUsers, login, logout, type Options, refreshToken, removeBusinessMember, updateBusiness, updateBusinessMemberRole, updateMe } from '../sdk.gen';
import type { ChangePasswordData, ChangePasswordError, ChangePasswordResponse, CreateBusinessData, CreateBusinessError, CreateBusinessResponse, CreateUserData, CreateUserError, CreateUserResponse, GetBusinessData, GetBusinessError, GetBusinessResponse, GetMeData, GetMeError, GetMeResponse, InviteBusinessMemberData, InviteBusinessMemberError, InviteBusinessMemberResponse, ListBusinessMembersData, ListBusinessMembersError, ListBusinessMembersResponse, ListMyBusinessesData, ListMyBusinessesError, ListMyBusinessesResponse, ListUsersData, ListUsersError, ListUsersResponse, LoginData, LoginError, LoginResponse, LogoutData, LogoutResponse, RefreshTokenData, RefreshTokenError, RefreshTokenResponse, RemoveBusinessMemberData, RemoveBusinessMemberError, RemoveBusinessMemberResponse, UpdateBusinessData, UpdateBusinessError, UpdateBusinessMemberRoleData, UpdateBusinessMemberRoleError, UpdateBusinessMemberRoleResponse, UpdateBusinessResponse, UpdateMeData, UpdateMeError, UpdateMeResponse } from '../types.gen';

export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const refreshTokenMutation = (options?: Partial<Options<RefreshTokenData>>): UseMutationOptions<RefreshTokenResponse, RefreshTokenError, Options<RefreshTokenData>> => {
    const mutationOptions: UseMutationOptions<RefreshTokenResponse, RefreshTokenError, Options<RefreshTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const changePasswordMutation = (options?: Partial<Options<ChangePasswordData>>): UseMutationOptions<ChangePasswordResponse, ChangePasswordError, Options<ChangePasswordData>> => {
    const mutationOptions: UseMutationOptions<ChangePasswordResponse, ChangePasswordError, Options<ChangePasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changePassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

export const getMeOptions = (options?: Options<GetMeData>) => queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeQueryKey(options)
});

export const updateMeMutation = (options?: Partial<Options<UpdateMeData>>): UseMutationOptions<UpdateMeResponse, UpdateMeError, Options<UpdateMeData>> => {
    const mutationOptions: UseMutationOptions<UpdateMeResponse, UpdateMeError, Options<UpdateMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse, ListUsersError, ListUsersResponse, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});

export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<CreateUserResponse, CreateUserError, Options<CreateUserData>> => {
    const mutationOptions: UseMutationOptions<CreateUserResponse, CreateUserError, Options<CreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listMyBusinessesQueryKey = (options?: Options<ListMyBusinessesData>) => createQueryKey('listMyBusinesses', options);

export const listMyBusinessesOptions = (options?: Options<ListMyBusinessesData>) => queryOptions<ListMyBusinessesResponse, ListMyBusinessesError, ListMyBusinessesResponse, ReturnType<typeof listMyBusinessesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listMyBusinesses({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMyBusinessesQueryKey(options)
});

export const createBusinessMutation = (options?: Partial<Options<CreateBusinessData>>): UseMutationOptions<CreateBusinessResponse, CreateBusinessError, Options<CreateBusinessData>> => {
    const mutationOptions: UseMutationOptions<CreateBusinessResponse, CreateBusinessError, Options<CreateBusinessData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBusiness({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBusinessQueryKey = (options: Options<GetBusinessData>) => createQueryKey('getBusiness', options);

export const getBusinessOptions = (options: Options<GetBusinessData>) => queryOptions<GetBusinessResponse, GetBusinessError, GetBusinessResponse, ReturnType<typeof getBusinessQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBusiness({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBusinessQueryKey(options)
});

export const updateBusinessMutation = (options?: Partial<Options<UpdateBusinessData>>): UseMutationOptions<UpdateBusinessResponse, UpdateBusinessError, Options<UpdateBusinessData>> => {
    const mutationOptions: UseMutationOptions<UpdateBusinessResponse, UpdateBusinessError, Options<UpdateBusinessData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBusiness({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBusinessMembersQueryKey = (options: Options<ListBusinessMembersData>) => createQueryKey('listBusinessMembers', options);

export const listBusinessMembersOptions = (options: Options<ListBusinessMembersData>) => queryOptions<ListBusinessMembersResponse, ListBusinessMembersError, ListBusinessMembersResponse, ReturnType<typeof listBusinessMembersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBusinessMembers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBusinessMembersQueryKey(options)
});

export const inviteBusinessMemberMutation = (options?: Partial<Options<InviteBusinessMemberData>>): UseMutationOptions<InviteBusinessMemberResponse, InviteBusinessMemberError, Options<InviteBusinessMemberData>> => {
    const mutationOptions: UseMutationOptions<InviteBusinessMemberResponse, InviteBusinessMemberError, Options<InviteBusinessMemberData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await inviteBusinessMember({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const removeBusinessMemberMutation = (options?: Partial<Options<RemoveBusinessMemberData>>): UseMutationOptions<RemoveBusinessMemberResponse, RemoveBusinessMemberError, Options<RemoveBusinessMemberData>> => {
    const mutationOptions: UseMutationOptions<RemoveBusinessMemberResponse, RemoveBusinessMemberError, Options<RemoveBusinessMemberData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeBusinessMember({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateBusinessMemberRoleMutation = (options?: Partial<Options<UpdateBusinessMemberRoleData>>): UseMutationOptions<UpdateBusinessMemberRoleResponse, UpdateBusinessMemberRoleError, Options<UpdateBusinessMemberRoleData>> => {
    const mutationOptions: UseMutationOptions<UpdateBusinessMemberRoleResponse, UpdateBusinessMemberRoleError, Options<UpdateBusinessMemberRoleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBusinessMemberRole({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
