// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, CreateBusinessData, CreateBusinessErrors, CreateBusinessResponses, CreateUserData, CreateUserErrors, CreateUserResponses, GetBusinessData, GetBusinessErrors, GetBusinessResponses, GetMeData, GetMeErrors, GetMeResponses, InviteBusinessMemberData, InviteBusinessMemberErrors, InviteBusinessMemberResponses, ListBusinessMembersData, ListBusinessMembersErrors, ListBusinessMembersResponses, ListMyBusinessesData, ListMyBusinessesErrors, ListMyBusinessesResponses, ListUsersData, ListUsersErrors, ListUsersResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses, RemoveBusinessMemberData, RemoveBusinessMemberErrors, RemoveBusinessMemberResponses, UpdateBusinessData, UpdateBusinessErrors, UpdateBusinessMemberRoleData, UpdateBusinessMemberRoleErrors, UpdateBusinessMemberRoleResponses, UpdateBusinessResponses, UpdateMeData, UpdateMeErrors, UpdateMeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>): RequestResult<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError> => (options.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    url: '/api/v1/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> => (options.client ?? client).patch<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

export const updateMe = <ThrowOnError extends boolean = false>(options: Options<UpdateMeData, ThrowOnError>): RequestResult<UpdateMeResponses, UpdateMeErrors, ThrowOnError> => (options.client ?? client).patch<UpdateMeResponses, UpdateMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/',
    ...options
});

export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listMyBusinesses = <ThrowOnError extends boolean = false>(options?: Options<ListMyBusinessesData, ThrowOnError>): RequestResult<ListMyBusinessesResponses, ListMyBusinessesErrors, ThrowOnError> => (options?.client ?? client).get<ListMyBusinessesResponses, ListMyBusinessesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/businesses/',
    ...options
});

export const createBusiness = <ThrowOnError extends boolean = false>(options: Options<CreateBusinessData, ThrowOnError>): RequestResult<CreateBusinessResponses, CreateBusinessErrors, ThrowOnError> => (options.client ?? client).post<CreateBusinessResponses, CreateBusinessErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/businesses/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getBusiness = <ThrowOnError extends boolean = false>(options: Options<GetBusinessData, ThrowOnError>): RequestResult<GetBusinessResponses, GetBusinessErrors, ThrowOnError> => (options.client ?? client).get<GetBusinessResponses, GetBusinessErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/businesses/{businessId}',
    ...options
});

export const updateBusiness = <ThrowOnError extends boolean = false>(options: Options<UpdateBusinessData, ThrowOnError>): RequestResult<UpdateBusinessResponses, UpdateBusinessErrors, ThrowOnError> => (options.client ?? client).patch<UpdateBusinessResponses, UpdateBusinessErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/businesses/{businessId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listBusinessMembers = <ThrowOnError extends boolean = false>(options: Options<ListBusinessMembersData, ThrowOnError>): RequestResult<ListBusinessMembersResponses, ListBusinessMembersErrors, ThrowOnError> => (options.client ?? client).get<ListBusinessMembersResponses, ListBusinessMembersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/businesses/{businessId}/members',
    ...options
});

export const inviteBusinessMember = <ThrowOnError extends boolean = false>(options: Options<InviteBusinessMemberData, ThrowOnError>): RequestResult<InviteBusinessMemberResponses, InviteBusinessMemberErrors, ThrowOnError> => (options.client ?? client).post<InviteBusinessMemberResponses, InviteBusinessMemberErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/businesses/{businessId}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const removeBusinessMember = <ThrowOnError extends boolean = false>(options: Options<RemoveBusinessMemberData, ThrowOnError>): RequestResult<RemoveBusinessMemberResponses, RemoveBusinessMemberErrors, ThrowOnError> => (options.client ?? client).delete<RemoveBusinessMemberResponses, RemoveBusinessMemberErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/businesses/{businessId}/members/{userId}',
    ...options
});

export const updateBusinessMemberRole = <ThrowOnError extends boolean = false>(options: Options<UpdateBusinessMemberRoleData, ThrowOnError>): RequestResult<UpdateBusinessMemberRoleResponses, UpdateBusinessMemberRoleErrors, ThrowOnError> => (options.client ?? client).patch<UpdateBusinessMemberRoleResponses, UpdateBusinessMemberRoleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/businesses/{businessId}/members/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
