// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8014' | (string & {});
};

export type LoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            accessToken: string;
            refreshToken: string;
        };
    };
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshTokenData = {
    body: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            accessToken: string;
            refreshToken: string;
        };
    };
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
    body: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Default Response
     */
    204: 'null';
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ChangePasswordData = {
    body: {
        oldPassword: string;
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
    /**
     * Konflik data (mis. email sudah dipakai)
     */
    409: {
        error: string;
        message: string;
    };
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Default Response
     */
    204: 'null';
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetMeErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            name: string;
            email: string;
        };
    };
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateMeData = {
    body: {
        name?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateMeErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            name: string;
            email: string;
        };
    };
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type ListUsersErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<{
            id: string;
            name: string;
            email: string;
        }>;
    };
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: {
        name: string;
        email: string;
        assignments: Array<{
            businessId: string;
            role: 'admin' | 'accountant' | 'viewer';
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
    /**
     * Sudah login, tapi tidak punya izin
     */
    403: {
        error: string;
        message: string;
    };
    /**
     * Konflik data (mis. email sudah dipakai)
     */
    409: {
        error: string;
        message: string;
    };
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Default Response
     */
    201: {
        data: {
            id: string;
            name: string;
            email: string;
        };
    };
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ListMyBusinessesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/businesses/';
};

export type ListMyBusinessesErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
};

export type ListMyBusinessesError = ListMyBusinessesErrors[keyof ListMyBusinessesErrors];

export type ListMyBusinessesResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<{
            id: string;
            name: string;
            baseCurrencyCode: string;
            role?: 'admin' | 'accountant' | 'viewer';
        }>;
    };
};

export type ListMyBusinessesResponse = ListMyBusinessesResponses[keyof ListMyBusinessesResponses];

export type CreateBusinessData = {
    body: {
        name: string;
        baseCurrencyCode?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/businesses/';
};

export type CreateBusinessErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
};

export type CreateBusinessError = CreateBusinessErrors[keyof CreateBusinessErrors];

export type CreateBusinessResponses = {
    /**
     * Default Response
     */
    201: {
        data: {
            id: string;
            name: string;
            baseCurrencyCode: string;
            role?: 'admin' | 'accountant' | 'viewer';
        };
    };
};

export type CreateBusinessResponse = CreateBusinessResponses[keyof CreateBusinessResponses];

export type GetBusinessData = {
    body?: never;
    path: {
        businessId: string;
    };
    query?: never;
    url: '/api/v1/businesses/{businessId}';
};

export type GetBusinessErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
    /**
     * Data tidak ditemukan
     */
    404: {
        error: string;
        message: string;
    };
};

export type GetBusinessError = GetBusinessErrors[keyof GetBusinessErrors];

export type GetBusinessResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            name: string;
            baseCurrencyCode: string;
            role?: 'admin' | 'accountant' | 'viewer';
        };
    };
};

export type GetBusinessResponse = GetBusinessResponses[keyof GetBusinessResponses];

export type UpdateBusinessData = {
    body: {
        name?: string;
        baseCurrencyCode?: string;
    };
    path: {
        businessId: string;
    };
    query?: never;
    url: '/api/v1/businesses/{businessId}';
};

export type UpdateBusinessErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
    /**
     * Sudah login, tapi tidak punya izin
     */
    403: {
        error: string;
        message: string;
    };
    /**
     * Data tidak ditemukan
     */
    404: {
        error: string;
        message: string;
    };
};

export type UpdateBusinessError = UpdateBusinessErrors[keyof UpdateBusinessErrors];

export type UpdateBusinessResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            name: string;
            baseCurrencyCode: string;
            role?: 'admin' | 'accountant' | 'viewer';
        };
    };
};

export type UpdateBusinessResponse = UpdateBusinessResponses[keyof UpdateBusinessResponses];

export type ListBusinessMembersData = {
    body?: never;
    path: {
        businessId: string;
    };
    query?: never;
    url: '/api/v1/businesses/{businessId}/members';
};

export type ListBusinessMembersErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
    /**
     * Data tidak ditemukan
     */
    404: {
        error: string;
        message: string;
    };
};

export type ListBusinessMembersError = ListBusinessMembersErrors[keyof ListBusinessMembersErrors];

export type ListBusinessMembersResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<{
            userId: string;
            name: string;
            email: string;
            role: 'admin' | 'accountant' | 'viewer';
            status: string;
        }>;
    };
};

export type ListBusinessMembersResponse = ListBusinessMembersResponses[keyof ListBusinessMembersResponses];

export type InviteBusinessMemberData = {
    body: {
        email: string;
        role: 'admin' | 'accountant' | 'viewer';
    };
    path: {
        businessId: string;
    };
    query?: never;
    url: '/api/v1/businesses/{businessId}/members';
};

export type InviteBusinessMemberErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
    /**
     * Sudah login, tapi tidak punya izin
     */
    403: {
        error: string;
        message: string;
    };
    /**
     * Data tidak ditemukan
     */
    404: {
        error: string;
        message: string;
    };
    /**
     * Konflik data (mis. email sudah dipakai)
     */
    409: {
        error: string;
        message: string;
    };
};

export type InviteBusinessMemberError = InviteBusinessMemberErrors[keyof InviteBusinessMemberErrors];

export type InviteBusinessMemberResponses = {
    /**
     * Default Response
     */
    201: {
        data: Array<{
            userId: string;
            name: string;
            email: string;
            role: 'admin' | 'accountant' | 'viewer';
            status: string;
        }>;
    };
};

export type InviteBusinessMemberResponse = InviteBusinessMemberResponses[keyof InviteBusinessMemberResponses];

export type RemoveBusinessMemberData = {
    body?: never;
    path: {
        businessId: string;
        userId: string;
    };
    query?: never;
    url: '/api/v1/businesses/{businessId}/members/{userId}';
};

export type RemoveBusinessMemberErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
    /**
     * Sudah login, tapi tidak punya izin
     */
    403: {
        error: string;
        message: string;
    };
    /**
     * Data tidak ditemukan
     */
    404: {
        error: string;
        message: string;
    };
};

export type RemoveBusinessMemberError = RemoveBusinessMemberErrors[keyof RemoveBusinessMemberErrors];

export type RemoveBusinessMemberResponses = {
    /**
     * Default Response
     */
    204: 'null';
};

export type RemoveBusinessMemberResponse = RemoveBusinessMemberResponses[keyof RemoveBusinessMemberResponses];

export type UpdateBusinessMemberRoleData = {
    body: {
        role: 'admin' | 'accountant' | 'viewer';
    };
    path: {
        businessId: string;
        userId: string;
    };
    query?: never;
    url: '/api/v1/businesses/{businessId}/members/{userId}';
};

export type UpdateBusinessMemberRoleErrors = {
    /**
     * Belum login / token tidak valid
     */
    401: {
        error: string;
        message: string;
    };
    /**
     * Sudah login, tapi tidak punya izin
     */
    403: {
        error: string;
        message: string;
    };
    /**
     * Data tidak ditemukan
     */
    404: {
        error: string;
        message: string;
    };
};

export type UpdateBusinessMemberRoleError = UpdateBusinessMemberRoleErrors[keyof UpdateBusinessMemberRoleErrors];

export type UpdateBusinessMemberRoleResponses = {
    /**
     * Default Response
     */
    204: 'null';
};

export type UpdateBusinessMemberRoleResponse = UpdateBusinessMemberRoleResponses[keyof UpdateBusinessMemberRoleResponses];
